// sh-gen scans source/script files for @shgen annotations and generates
// a bash completion script from the discovered CLI structure.
//
// Usage:
//
//	sh-gen [flags] <file> [file...]
//
// Flags:
//
//	-o, --output  <file>   Write output to <file> instead of stdout.
//	-O, --store            Store output in ~/.config/t-l3/sh-gen/{[name].comp.sh,[name].lazycomp.sh}.
//	-p, --process <name>   Override the program name used in the completion script.
//	-g, --grouped          Prefix command and argument groups with semantic labels.
//	-s, --silent           Do not print top-level legend output to stderr after generation.
//	-h, --help             Show this help message.
//
// @shgen module sh-gen Scans source files for @shgen annotations and generates bash completion scripts
// @shgen argument parent=sh-gen complete=file alternate=-o --output  Write completion output to a file instead of stdout
// @shgen argument parent=sh-gen               alternate=-O --store   Store completion output in ~/.config/t-l3/sh-gen/{[name].comp.sh,[name].lazycomp.sh}
// @shgen argument parent=sh-gen complete=none alternate=-p --process Override the program name used in the generated completion script
// @shgen argument parent=sh-gen               alternate=-g --grouped Group completion output into completion types
// @shgen argument parent=sh-gen               alternate=-s --silent  Suppress top-level legend output to stderr
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/t-l3/sh-gen/internal/annotation"
	"github.com/t-l3/sh-gen/internal/generator"
	"github.com/t-l3/sh-gen/internal/model"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "sh-gen: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	var (
		outputFile     string
		storeOutput    bool
		programName    string
		semanticGroups bool
		silent         bool
	)

	flag.StringVar(&outputFile, "output", "", "Write output to `file` instead of stdout")
	flag.StringVar(&outputFile, "o", outputFile, "See -output `file`")
	flag.BoolVar(&storeOutput, "store", false, "Store output in ~/.config/t-l3/sh-gen/{[name].comp.sh,[name].lazycomp.sh}")
	flag.BoolVar(&storeOutput, "O", storeOutput, "See --store")
	flag.StringVar(&programName, "process", "", "Override the program `name` used in the completion script")
	flag.StringVar(&programName, "p", programName, "See -process `name`")
	flag.BoolVar(&semanticGroups, "grouped", false, "Group completion output into completion types")
	flag.BoolVar(&semanticGroups, "g", semanticGroups, "See --grouped")
	flag.BoolVar(&silent, "silent", false, "Suppress top-level legend output to stderr")
	flag.BoolVar(&silent, "s", silent, "See --silent")
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: sh-gen [flags] <file> [file...]\n\n")
		fmt.Fprintf(os.Stderr, "Scans files for @shgen annotations and generates a bash completion script.\n\n")
		fmt.Fprintf(os.Stderr, "Flags:\n")
		flag.PrintDefaults()
	}
	flag.Parse()

	files := flag.Args()
	if len(files) == 0 {
		flag.Usage()
		return fmt.Errorf("at least one input file is required")
	}

	// Scan all input files for annotations.
	var allAnnotations []annotation.Annotation
	for _, path := range files {
		f, err := os.Open(path)
		if err != nil {
			return fmt.Errorf("opening %s: %w", path, err)
		}
		anns, err := annotation.Scan(f, path)
		f.Close()
		if err != nil {
			return fmt.Errorf("scanning %s: %w", path, err)
		}
		allAnnotations = append(allAnnotations, anns...)
	}

	// Build the completion model.
	tree, err := model.Build(allAnnotations)
	if err != nil {
		return fmt.Errorf("building model: %w", err)
	}

	// Determine output writer.
	out := os.Stdout
	if outputFile != "" {
		f, err := os.Create(outputFile)
		if err != nil {
			return fmt.Errorf("creating output file %s: %w", outputFile, err)
		}
		defer f.Close()
		out = f
	}

	// Generate the bash completion script.
	opts := generator.Options{
		ProgramName:       programName,
		UseSemanticGroups: semanticGroups,
	}
	var generated bytes.Buffer
	if err := generator.Generate(&generated, tree, opts); err != nil {
		return fmt.Errorf("generating completion script: %w", err)
	}

	if _, err := out.Write(generated.Bytes()); err != nil {
		return fmt.Errorf("writing generated completion script: %w", err)
	}

	if storeOutput {
		if err := storeGeneratedScript(generated.String()); err != nil {
			return fmt.Errorf("storing generated completion script: %w", err)
		}
	}

	if !silent {
		if err := printTopLevelLegend(os.Stderr, generated.String()); err != nil {
			return fmt.Errorf("printing top-level legend: %w", err)
		}
	}

	return nil
}

var completeBindingRE = regexp.MustCompile(`(?m)^complete -F ([^[:space:]]+) ([^[:space:]]+)\s*$`)

func storeGeneratedScript(script string) error {
	completionFunc, program, err := discoverCompletionBinding(script)
	if err != nil {
		return err
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("resolving user home directory: %w", err)
	}

	storeDir := filepath.Join(home, ".config", "t-l3", "sh-gen")
	if err := os.MkdirAll(storeDir, 0o755); err != nil {
		return fmt.Errorf("creating store directory %s: %w", storeDir, err)
	}

	storePath := filepath.Join(storeDir, program+".comp.sh")
	if err := os.WriteFile(storePath, []byte(script), 0o644); err != nil {
		return fmt.Errorf("writing store file %s: %w", storePath, err)
	}

	lazyPath := filepath.Join(storeDir, program+".lazycomp.sh")
	lazyScript := buildLazyCompletionScript(program, completionFunc, storePath)
	if err := os.WriteFile(lazyPath, []byte(lazyScript), 0o644); err != nil {
		return fmt.Errorf("writing lazy store file %s: %w", lazyPath, err)
	}

	return nil
}

func discoverCompletionBinding(script string) (completionFunc string, program string, err error) {
	match := completeBindingRE.FindStringSubmatch(script)
	if len(match) != 3 {
		return "", "", fmt.Errorf("could not discover completion binding in generated script")
	}
	return match[1], match[2], nil
}

func buildLazyCompletionScript(program string, completionFunc string, completionPath string) string {
	lazyCompletionFunc := completionFunc + "_lazy"
	return fmt.Sprintf(`%s() {
	if ! declare -F %s >/dev/null; then
		source %q
	fi
	%s "$@"
}
complete -F %s %s
`, lazyCompletionFunc, completionFunc, completionPath, completionFunc, lazyCompletionFunc, program)
}

func printTopLevelLegend(dst *os.File, script string) error {
	match := completeBindingRE.FindStringSubmatch(script)
	if len(match) != 3 {
		return fmt.Errorf("could not discover completion binding in generated script")
	}
	completionFunc := match[1]
	program := match[2]

	tmp, err := os.CreateTemp("", "sh-gen-completion-*.bash")
	if err != nil {
		return fmt.Errorf("creating temporary completion file: %w", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)

	if _, err := tmp.WriteString(script); err != nil {
		tmp.Close()
		return fmt.Errorf("writing temporary completion file: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("closing temporary completion file: %w", err)
	}

	legendCommand := fmt.Sprintf(`_get_comp_words_by_ref() {
	. $HOME/.bashrc &> /dev/null
	local OPTIND opt no
	while getopts "n:" opt; do
		case "$opt" in
			n) no="$OPTARG" ;;
		esac
	done
	shift $((OPTIND-1))

	local _cur_ref=$1
	local _prev_ref=$2
	local _words_ref=$3
	local _cword_ref=$4

	local _cur _prev
	_cur="${COMP_WORDS[COMP_CWORD]}"
	if (( COMP_CWORD > 0 )); then
		_prev="${COMP_WORDS[COMP_CWORD-1]}"
	else
		_prev=""
	fi

	eval "$_cur_ref=\"\$_cur\""
	eval "$_prev_ref=\"\$_prev\""
	eval "$_words_ref=(\"\${COMP_WORDS[@]}\")"
	eval "$_cword_ref=\$COMP_CWORD"
}
source %q
COMP_LINE=%q
COMP_POINT=${#COMP_LINE}
COMP_WORDS=(%q "")
COMP_CWORD=1
COMPREPLY=()
%s`, tmpPath, program+" ", program, completionFunc)

	cmd := exec.Command("bash", "-lc", legendCommand)
	legendOutput, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("executing generated completion function: %w: %s", err, strings.TrimSpace(string(legendOutput)))
	}

	if len(legendOutput) == 0 {
		return nil
	}

	if _, err := dst.Write(legendOutput); err != nil {
		return fmt.Errorf("writing legend to stderr: %w", err)
	}
	return nil
}
