#!/usr/bin/bash

# @shgen module k A shorthand kubectl wrapper to provide additional functionality for users

# Generated output straight from sh-gen on fd 2/stderr
_k_help_message() {
  cat <<EOF
k - A shorthand kubectl wrapper to provide additional functionality for users

  [tab] Show contextual help

Available commands:
           secret       (Print the string value for each key in a given secret or for the provided key)
              all       (Print all resources)

Additional completion:
            [...]       (All kubectl commands)
EOF
return 0;
}

k() {
  local _K_WRAPPER_KUBECTL_BINARY="$(type -p kubectl || "kubectl")"
  if [[ ! "$1" ]]; then
    _k_help_message;
    return 0
  fi

  # @shgen external  _k_wrapper_current_namespace() { local found=0 i word; _K_NS=(); for ((i=1; i<=COMP_CWORD; i++)); do word="${COMP_WORDS[i]}"; if [[ "$found" -eq 1 ]]; then [[ -n "$word" ]] && _K_NS=("-n" "$word"); return 0; fi; if [[ "$word" == "-n" || "$word" == "--namespace" ]]; then found=1; fi; done; }
  while [[ "$1" ]]; do
    case "$1" in
      # @shgen validation kube-ns                                                             bash -c 'kubectl get namespaces -o custom-columns=NAME:.metadata.name --no-headers'
      # @shgen command                  complete=kube-ns                         ns           Switch current context to a given namespace
      ns)
        shift
        if [[ "$1" ]]; then
          "$_K_WRAPPER_KUBECTL_BINARY" config set-context --current --namespace "$1"
          return $?
        fi
        ;;
      # @shgen validation kube-secrets                                                        local _K_NS=(); _k_wrapper_current_namespace; kubectl get secrets "${_K_NS[@]}" -o custom-columns=NAME:.metadata.name --no-headers
      # @shgen validation kube-secrets-static                                                 bash -c 'echo -e "exampleSecret\nmySecret\ntestSecret"'
      # @shgen validation kube-secret-keys                                                    local _K_NS=(); _k_wrapper_current_namespace; kubectl get secrets "${_K_NS[@]}" -o json | jq -r ".items[].data | keys[]"
      # @shgen validation kube-secret-keys-static                                             bash -c 'echo -e "key1\npublic.crt\nprivate.key"; exit 0;'
      # @shgen command                  complete=kube-secrets                    secret       Print the string value for each key in a given secret or for the provided key
      # @shgen argument  parent=secret  complete=kube-secret-keys  alternate=-k  --key        Specific key from the given secret
      # @shgen argument  parent=secret  complete=kube-ns           alternate=-n  --namespace  Namespace containing the secret resource
      secret)
        shift
        local _K_WRAPPER_SECRET_NAME _K_WRAPPER_SECRET_KEY _K_WRAPPER_SECRET_NAMESPACE=()
        while [[ "$1" ]]; do
          case "$1" in
            -n|--namespace)
              shift
              if [[ "$1" ]]; then
                _K_WRAPPER_SECRET_NAMESPACE=("-n" "$1")
                shift
              else
                echo "No namespace provided" >&2
                return 1;
              fi
              continue
              ;;
            -k|--key)
              shift
              if [[ "$1" ]]; then
                _K_WRAPPER_SECRET_KEY="| .[\"$1\"]"
                shift
                continue
              else
                echo "No key provided" >&2
                return 1;
              fi
              continue
              ;;
            *)
              _K_WRAPPER_SECRET_NAME="$1"
              shift
              continue
              ;;
          esac
        done

        if [[ ! "$_K_WRAPPER_SECRET_NAME" ]]; then
          echo "No secret name specified" >&2
        fi
        

        "$_K_WRAPPER_KUBECTL_BINARY" get secret "${_K_WRAPPER_SECRET_NAMESPACE[@]}" "$_K_WRAPPER_SECRET_NAME" -o json \
          | jq -r '.data[] |= @base64d | .data'"$_K_WRAPPER_SECRET_KEY"

        return 0
        ;;
      # @shgen command all Print all resources
      all)
        # logic
        return 0
        ;;
      # @shgen external _k_kubectl_passthrough() { __start_kubectl; }
      # @shgen validation kubectl-passthrough _k_kubectl_passthrough
      # @shgen wildcard parent=k complete=kubectl-passthrough masquerade=kubectl
      *)
        "$_K_WRAPPER_KUBECTL_BINARY" "$@"
        return "$?"
        ;;
    esac
  done
}

if [[ "$1" ]]; then
  k "$@"
else
  _k_help_message
fi
