package generator

import (
	"bytes"
	"io"
	"strings"
	"text/template"

	"github.com/t-l3/sh-gen/internal/model"
)

// Options controls generation behaviour.
type Options struct {
	ProgramName       string
	UseSemanticGroups bool
}

const bashTemplate = `
#!/usr/bin/env bash
# Generated by sh-gen — do not edit manually.

{{ range .Externals }}
{{ . }}
{{ end }}

{{ range .Validations }}
{{ .FuncName }}() {
    {{ .Script }}
}
{{ end }}

 _{{ .FuncName }}_completion() {
    local cur prev words cword max_opt_width="{{ .MaxOptWidth }}"
    local __shgen_printed=0

    # Preserve original word breaks for delegated completions (e.g. kubectl).
    local _shgen_orig_COMP_WORDBREAKS="$COMP_WORDBREAKS"

    COMPREPLY=()
    # Parse our own context with ':' and '-' treated as part of words.
    _get_comp_words_by_ref -n :- cur prev words cword 2>/dev/null || return

    if [[ "$cur" == *$'\e['* ]]; then
        return 0
    fi

    local known_paths=(
        {{- range .KnownPaths }}
        "{{ . }}"
        {{- end }}
    )

    local context=""
    local current_path=""
    local __shgen_unrecognized_path=0
    for (( i=1; i < cword; i++ )); do
        case "${words[i]}" in
            -*) ;;
            "") ;;
            *)
                local next_path="${current_path}${words[i]}"
                local found=0
                for p in "${known_paths[@]}"; do
                    if [[ "$p" == "$next_path" ]]; then
                        found=1
                        break
                    fi
                done
                if [[ $found -eq 1 ]]; then
                    current_path="${next_path} "
                else
                    __shgen_unrecognized_path=1
                    break
                fi
                ;;
        esac
    done
    context="${current_path}"

    # Normalize context: remove trailing space for matching
    local normalized_context="${context% }"
    case "$normalized_context" in
        {{- range $node := .Nodes }}
        "{{ trimTrailingSpace $node.Path }}")
            local -a __shgen_matched=()
            local __shgen_suppress_local=0
            {{- if .Wildcard }}
            if [[ $__shgen_unrecognized_path -eq 1 ]]; then
                __shgen_suppress_local=1
            fi
            {{- end }}

            # Explicit completion override for argument values.
            case "$prev" in
                {{- range .Arguments }}
                {{- $argComplete := argCompletion . }}
                {{- if and (ne .Name "") (ne $argComplete "") }}
                "{{ .Name }}"{{ if .Alternate }}|"{{ .Alternate }}"{{ end }})
                    {{- if eq (completionKind $argComplete) "file" }}
                    compopt -o filenames 2>/dev/null
                    COMPREPLY=( $(compgen -f -- "$cur") )
                    {{- else if eq (completionKind $argComplete) "none" }}
                    COMPREPLY=()
                    {{- else if eq (completionKind $argComplete) "function" }}
                    local __shgen_values="$({{ completionFunc $argComplete }} 2>/dev/null)"
                    COMPREPLY=( $(compgen -W "$__shgen_values" -- "$cur") )
                {{- if completionNoSpace $argComplete }}
                compopt -o nospace 2>/dev/null
                {{- end }}
                    {{- end }}
                    return 0
                    ;;
                {{- end }}
                {{- end }}
            esac

            # Explicit completion override for command value.
            {{- if ne .CommandComplete "" }}
            if [[ "$normalized_context" == "{{ trimTrailingSpace $node.Path }}" && "$prev" == "{{ .Name }}" && "$cur" != -* ]]; then
                {{- if eq (completionKind .CommandComplete) "file" }}
                compopt -o filenames 2>/dev/null
                COMPREPLY=( $(compgen -f -- "$cur") )
                {{- else if eq (completionKind .CommandComplete) "none" }}
                COMPREPLY=()
                {{- else if eq (completionKind .CommandComplete) "function" }}
                local __shgen_values="$({{ completionFunc .CommandComplete }} 2>/dev/null)"
                COMPREPLY=( $(compgen -W "$__shgen_values" -- "$cur") )
                {{- if completionNoSpace .CommandComplete }}
                compopt -o nospace 2>/dev/null
                {{- end }}
                {{- end }}
                return 0
            fi
            {{- end }}

            # Explicit completion override for module first positional value.
            # Trigger when user is typing the first token after this module path.
            {{- if ne .ModuleComplete "" }}
            if [[ "$normalized_context" == "{{ trimTrailingSpace $node.Path }}" && $cword -eq $(({{ pathWordCount $node.Path }} + 1)) && "$cur" != -* ]]; then
                {{- if eq (completionKind .ModuleComplete) "file" }}
                compopt -o filenames 2>/dev/null
                COMPREPLY=( $(compgen -f -- "$cur") )
                {{- else if eq (completionKind .ModuleComplete) "none" }}
                COMPREPLY=()
                {{- else if eq (completionKind .ModuleComplete) "function" }}
                local __shgen_values="$({{ completionFunc .ModuleComplete }} 2>/dev/null)"
                COMPREPLY=( $(compgen -W "$__shgen_values" -- "$cur") )
                {{- if completionNoSpace .ModuleComplete }}
                compopt -o nospace 2>/dev/null
                {{- end }}
                {{- end }}
                return 0
            fi
            {{- end }}

            {{- if .Description }}
            if [[ "$cur" == "" && "$normalized_context" == "{{ trimTrailingSpace $node.Path }}" && $__shgen_suppress_local -eq 0 ]]; then
                if [[ $__shgen_printed -eq 0 ]]; then
                    printf "\n"
                    __shgen_printed=1
                fi
                echo -e "{{ .Name }} - {{ .Description }}"
                echo -e "\n  [tab]\tShow contextual help"
            fi
            {{- end }}
            {{- if .SubModules }}
            {{ if $.UseSemanticGroups }}if [[ "$cur" == "" && "$normalized_context" == "{{ trimTrailingSpace $node.Path }}" && $__shgen_suppress_local -eq 0 ]]; then echo -e "\nAvailable modules:"; fi{{ end }}
            {{- range .SubModules }}
            if [[ "{{ .Name }}" == "$cur"* && "$normalized_context" == "{{ trimTrailingSpace $node.Path }}" && $__shgen_suppress_local -eq 0 ]]; then
                __shgen_matched+=("{{ .Name }}")
                if [[ $__shgen_printed -eq 0 ]]; then
                    printf "\n"
                    __shgen_printed=1
                fi
                printf "%${max_opt_width}s\t%s\n" "{{ .Name }}" "({{ .Description }})"
            fi
            {{- end }}
            {{- end }}
            {{- if .Commands }}
            {{ if $.UseSemanticGroups }}if [[ "$cur" == "" && "$normalized_context" == "{{ trimTrailingSpace $node.Path }}" && $__shgen_suppress_local -eq 0 ]]; then echo -e "\nAvailable commands:"; fi{{ end }}
            {{- range .Commands }}
            if [[ "{{ .Name }}" == "$cur"* && "$normalized_context" == "{{ trimTrailingSpace $node.Path }}" && $__shgen_suppress_local -eq 0 ]]; then
                __shgen_matched+=("{{ .Name }}")
                if [[ $__shgen_printed -eq 0 ]]; then
                    printf "\n"
                    __shgen_printed=1
                fi
                printf "%${max_opt_width}s\t%s\n" "{{ .Name }}" "({{ .Description }})"
            fi
            {{- end }}
            {{- end }}
            {{- if .Arguments }}
            {{ if $.UseSemanticGroups }}if [[ "$cur" == "" && "$normalized_context" == "{{ trimTrailingSpace $node.Path }}" && $__shgen_suppress_local -eq 0 ]]; then echo -e "\nAvailable arguments:"; fi{{ end }}
            {{- range .Arguments }}
            local __shgen_arg_matches=0
            local __shgen_name_matches=0
            local __shgen_alt_matches=0
            if [[ "{{ .Name }}" == "$cur"* && "$normalized_context" == "{{ trimTrailingSpace $node.Path }}" && $__shgen_suppress_local -eq 0 ]]; then
                __shgen_arg_matches=1
                __shgen_name_matches=1
            fi
            {{- if .Alternate }}
            if [[ "{{ .Alternate }}" == "$cur"* && "$normalized_context" == "{{ trimTrailingSpace $node.Path }}" && $__shgen_suppress_local -eq 0 ]]; then
                __shgen_arg_matches=1
                __shgen_alt_matches=1
            fi
            {{- end }}
            if [[ $__shgen_arg_matches -eq 1 ]]; then
                if [[ $__shgen_name_matches -eq 1 ]]; then
                    __shgen_matched+=("{{ .Name }}")
                fi
                {{- if .Alternate }}
                if [[ $__shgen_alt_matches -eq 1 ]]; then
                    __shgen_matched+=("{{ .Alternate }}")
                fi
                {{- end }}
                if [[ $__shgen_printed -eq 0 ]]; then
                    printf "\n"
                    __shgen_printed=1
                fi
                printf "%${max_opt_width}s\t%s\n" "{{ .Name }}{{ if .Alternate }}, {{ .Alternate }}{{ end}}" "({{ .Description }})"
            fi
            {{- end }}
            {{- end }}
            {{- if .Wildcard }}
            # Wildcard completion
            local __shgen_pre_wildcard_count=${#COMPREPLY[@]}

            # Prefer masqueraded completion first (e.g. kubectl) for deeper paths.
            if [[ "{{ .Wildcard.Masquerade }}" != "" ]]; then
                local _shgen_masq_func=$(complete -p {{ .Wildcard.Masquerade }} 2>/dev/null | awk '{print $(NF-1)}')
                if [[ -n "$_shgen_masq_func" ]]; then
                    # Calculate how many words to skip from the original command
                    local _shgen_matched_path_word_count=1
                    if [[ -n "$normalized_context" ]]; then
                        local _shgen_matched_path_array=($normalized_context)
                        _shgen_matched_path_word_count=${#_shgen_matched_path_array[@]}
                        # Add 1 because the context doesn't include the program name itself at the root
                        ((_shgen_matched_path_word_count++))
                    fi

                    # Save current state
                    local _shgen_orig_words=("${COMP_WORDS[@]}")
                    local _shgen_orig_cword=$COMP_CWORD
                    local _shgen_orig_line="$COMP_LINE"
                    local _shgen_orig_point=$COMP_POINT

                    # Construct new words: Masquerade command + everything after the matched path
                    COMP_WORDS=("{{ .Wildcard.Masquerade }}" "${_shgen_orig_words[@]:$_shgen_matched_path_word_count}")
                    # Preserve an explicit empty token for trailing-space completion.
                    if [[ "$cur" == "" ]]; then
                        COMP_WORDS+=("")
                    fi
                    COMP_CWORD=$(($_shgen_orig_cword - $_shgen_matched_path_word_count + 1))
                    COMP_LINE="${COMP_WORDS[*]}"
                    if [[ "$cur" == "" ]]; then
                        COMP_LINE+=" "
                    fi
                    COMP_POINT=${#COMP_LINE}

                    # Ensure delegated completer gets default word-break behaviour.
                    COMP_WORDBREAKS="$_shgen_orig_COMP_WORDBREAKS"

                    # Call the masqueraded completion function
                    "$_shgen_masq_func"

                    # Restore state
                    COMP_WORDS=("${_shgen_orig_words[@]}")
                    COMP_CWORD=$_shgen_orig_cword
                    COMP_LINE="$_shgen_orig_line"
                    COMP_POINT=$_shgen_orig_point

                    if [[ ${#COMPREPLY[@]} -gt $__shgen_pre_wildcard_count ]]; then
                        local __shgen_wc_has_values=0
                        for (( i=$__shgen_pre_wildcard_count; i < ${#COMPREPLY[@]}; i++ )); do
                            if [[ -n "${COMPREPLY[i]}" ]]; then
                                __shgen_wc_has_values=1
                                break
                            fi
                        done
                        if [[ $__shgen_wc_has_values -eq 1 ]]; then
                            {{ if $.UseSemanticGroups }}
                            if [[ "$cur" == "" && $__shgen_suppress_local -eq 0 ]]; then
                                echo -e "\nAdditional completion:"
                                __shgen_printed=1
                            fi
                            {{ end }}
                            if [[ $__shgen_printed -eq 0 ]]; then
                                printf "\n"
                            fi
                            __shgen_printed=1
                            local __shgen_wc_printed=0
                            # Print command/value suggestions first.
                            for (( i=$__shgen_pre_wildcard_count; i < ${#COMPREPLY[@]}; i++ )); do
                                local __shgen_wc_item="${COMPREPLY[i]}"
                                if [[ "$__shgen_wc_item" != -* && "$__shgen_wc_item" != \\-* && -n "$__shgen_wc_item" ]]; then
                                    printf "%s\n" "$__shgen_wc_item"
                                    __shgen_wc_printed=1
                                fi
                            done
                            # Print option suggestions (leading - / --) after commands.
                            for (( i=$__shgen_pre_wildcard_count; i < ${#COMPREPLY[@]}; i++ )); do
                                local __shgen_wc_item="${COMPREPLY[i]}"
                                if [[ "$__shgen_wc_item" == -* || "$__shgen_wc_item" == \\-* ]]; then
                                    printf "%s\n" "$__shgen_wc_item"
                                    __shgen_wc_printed=1
                                fi
                            done
                            # Fallback: if items exist but nothing matched the grouping filters, print raw.
                            if [[ $__shgen_wc_printed -eq 0 ]]; then
                                for (( i=$__shgen_pre_wildcard_count; i < ${#COMPREPLY[@]}; i++ )); do
                                    local __shgen_wc_item="${COMPREPLY[i]}"
                                    if [[ -n "$__shgen_wc_item" ]]; then
                                        printf "%s\n" "$__shgen_wc_item"
                                    fi
                                done
                            fi
                        fi
                    fi
                fi
            fi

            # Fallback to wildcard validator only when masquerade yielded nothing.
            if [[ ${#COMPREPLY[@]} -eq $__shgen_pre_wildcard_count ]]; then
                # Restore default word-break behaviour before delegating externally.
                COMP_WORDBREAKS="$_shgen_orig_COMP_WORDBREAKS"
                {{ .Wildcard.Complete }}
                if [[ ${#COMPREPLY[@]} -gt $__shgen_pre_wildcard_count ]]; then
                    local __shgen_wc_has_values=0
                    for (( i=$__shgen_pre_wildcard_count; i < ${#COMPREPLY[@]}; i++ )); do
                        if [[ -n "${COMPREPLY[i]}" ]]; then
                            __shgen_wc_has_values=1
                            break
                        fi
                    done
                    if [[ $__shgen_wc_has_values -eq 1 ]]; then
                        {{ if $.UseSemanticGroups }}
                        if [[ "$cur" == "" ]]; then
                            echo -e "\nAdditional completion:"
                            __shgen_printed=1
                        fi
                        {{ end }}
                        if [[ $__shgen_printed -eq 0 ]]; then
                            printf "\n"
                        fi
                        __shgen_printed=1
                        local __shgen_wc_printed=0
                        # Print command/value suggestions first.
                        for (( i=$__shgen_pre_wildcard_count; i < ${#COMPREPLY[@]}; i++ )); do
                            local __shgen_wc_item="${COMPREPLY[i]}"
                            if [[ "$__shgen_wc_item" != -* && "$__shgen_wc_item" != \\-* && -n "$__shgen_wc_item" ]]; then
                                printf "%s\n" "$__shgen_wc_item"
                                __shgen_wc_printed=1
                            fi
                        done
                        # Print option suggestions (leading - / --) after commands.
                        for (( i=$__shgen_pre_wildcard_count; i < ${#COMPREPLY[@]}; i++ )); do
                            local __shgen_wc_item="${COMPREPLY[i]}"
                            if [[ "$__shgen_wc_item" == -* || "$__shgen_wc_item" == \\-* ]]; then
                                printf "%s\n" "$__shgen_wc_item"
                                __shgen_wc_printed=1
                            fi
                        done
                        # Fallback: if items exist but nothing matched the grouping filters, print raw.
                        if [[ $__shgen_wc_printed -eq 0 ]]; then
                            for (( i=$__shgen_pre_wildcard_count; i < ${#COMPREPLY[@]}; i++ )); do
                                local __shgen_wc_item="${COMPREPLY[i]}"
                                if [[ -n "$__shgen_wc_item" ]]; then
                                    printf "%s\n" "$__shgen_wc_item"
                                fi
                            done
                        fi
                    fi
                fi
            fi
            {{- end }}

            if [[ $__shgen_printed -eq 1 && -n "$COMP_LINE" && -t 1 ]]; then
                bind '"\e[0n": redraw-current-line' 2>/dev/null
                printf "\e[5n"
            fi

            # Add our own matches back to COMPREPLY (in case wildcard function cleared it)
            COMPREPLY+=("${__shgen_matched[@]}")
            ;;
        {{- end }}
    esac
}

complete -F _{{ .FuncName }}_completion {{ .ProgramName }}
`

type node struct {
	Name            string
	Path            string
	Description     string
	ModuleComplete  string
	CommandComplete string
	SubModules      []*model.Module
	Commands        []*model.Command
	Arguments       []*model.Argument
	Wildcard        *tmplWildcard
}

type tmplWildcard struct {
	Complete   string
	Masquerade string
}

type tmplValidation struct {
	FuncName string
	Script   string
	NoSpace  bool
}

type templateData struct {
	ProgramName       string
	FuncName          string
	UseSemanticGroups bool
	MaxOptWidth       int
	Nodes             []node
	KnownPaths        []string
	Externals         []string
	Validations       []tmplValidation
}

// Generate writes a bash completion script for tree to w.
func Generate(w io.Writer, tree *model.Tree, opts Options) error {
	programName := opts.ProgramName
	if programName == "" {
		for _, m := range tree.Modules {
			if m.Parent == "" && m.Name != "" {
				programName = m.Name
				break
			}
		}
	}
	if programName == "" {
		programName = "program"
	}

	data := templateData{
		ProgramName:       programName,
		FuncName:          sanitizeFuncName(programName),
		UseSemanticGroups: opts.UseSemanticGroups,
		Externals:         tree.Externals,
	}

	for _, v := range tree.Validations {
		data.Validations = append(data.Validations, tmplValidation{
			FuncName: "_shgen_validate_" + sanitizeFuncName(v.Name),
			Script:   v.Script,
			NoSpace:  v.NoSpace,
		})
	}

	validationNoSpace := make(map[string]bool, len(tree.Validations))
	for name, v := range tree.Validations {
		if v != nil {
			validationNoSpace[name] = v.NoSpace
		}
	}

	// Collect nodes from root modules. We combine Modules[""] and Modules[programName]
	// if they both represent the root.
	rootNodesMap := make(map[string]node)
	roots := []*model.Module{tree.Modules[""], tree.Modules[programName]}
	for _, root := range roots {
		if root == nil {
			continue
		}
		// Process this root and its children
		for _, n := range collectNodes("", root) {
			if existing, ok := rootNodesMap[n.Path]; ok {
				// Merge content for same path
				existing.SubModules = append(existing.SubModules, n.SubModules...)
				existing.Commands = append(existing.Commands, n.Commands...)
				existing.Arguments = append(existing.Arguments, n.Arguments...)
				if n.ModuleComplete != "" {
					existing.ModuleComplete = n.ModuleComplete
				}
				if n.Wildcard != nil {
					existing.Wildcard = n.Wildcard
				}
				if n.Description != "" {
					existing.Description = n.Description
				}
				if n.Name != "" {
					existing.Name = n.Name
				}
				rootNodesMap[n.Path] = existing
			} else {
				rootNodesMap[n.Path] = n
			}
		}
	}

	// Flatten map back to slice
	for _, n := range rootNodesMap {
		data.Nodes = append(data.Nodes, n)
		data.KnownPaths = append(data.KnownPaths, strings.TrimSpace(n.Path))
	}

	resolveCompletion := func(raw string) (kind string, fn string) {
		raw = strings.TrimSpace(raw)
		if raw == "" {
			return "", ""
		}
		switch raw {
		case "file":
			return "file", ""
		case "none":
			return "none", ""
		default:
			if _, ok := tree.Validations[raw]; ok {
				return "function", "_shgen_validate_" + sanitizeFuncName(raw)
			}
			// Treat as externally declared completion function.
			return "function", raw
		}
	}

	funcMap := template.FuncMap{
		"trimTrailingSpace": func(s string) string {
			return strings.TrimSpace(s)
		},
		"argCompletion": func(a *model.Argument) string {
			if a == nil {
				return ""
			}
			if strings.TrimSpace(a.Complete) != "" {
				return strings.TrimSpace(a.Complete)
			}
			return strings.TrimSpace(a.Validate)
		},
		"completionKind": func(raw string) string {
			k, _ := resolveCompletion(raw)
			return k
		},
		"completionFunc": func(raw string) string {
			_, fn := resolveCompletion(raw)
			return fn
		},
		"completionNoSpace": func(raw string) bool {
			raw = strings.TrimSpace(raw)
			if raw == "" || raw == "file" || raw == "none" {
				return false
			}
			return validationNoSpace[raw]
		},
		"pathWordCount": func(path string) int {
			trimmed := strings.TrimSpace(path)
			if trimmed == "" {
				return 0
			}
			return len(strings.Fields(trimmed))
		},
	}

	data.MaxOptWidth = calculateMaxOptWidth(data.Nodes)

	tmpl, err := template.New("bash").Funcs(funcMap).Parse(strings.TrimSpace(bashTemplate))
	if err != nil {
		return err
	}

	return tmpl.Execute(w, data)
}

func collectNodes(parentPath string, m *model.Module) []node {
	n := node{
		Name:           m.Name,
		Path:           parentPath,
		Description:    m.Description,
		ModuleComplete: m.Complete,
		SubModules:     m.SubModules,
		Commands:       m.Commands,
		Arguments:      m.Arguments,
	}
	if m.Wildcard != nil {
		n.Wildcard = &tmplWildcard{
			Complete:   "_shgen_validate_" + sanitizeFuncName(m.Wildcard.Complete),
			Masquerade: m.Wildcard.Masquerade,
		}
	}
	nodes := []node{n}

	for _, sub := range m.SubModules {
		nodes = append(nodes, collectNodes(parentPath+sub.Name+" ", sub)...)
	}

	for _, cmd := range m.Commands {
		nodes = append(nodes, node{
			Name:            cmd.Name,
			Path:            parentPath + cmd.Name + " ",
			Description:     cmd.Description,
			CommandComplete: cmd.Complete,
			Arguments:       cmd.Arguments,
		})
	}

	return nodes
}

func calculateMaxOptWidth(nodes []node) int {
	maxWidth := 1
	for _, n := range nodes {
		for _, sm := range n.SubModules {
			if l := len(sm.Name); l > maxWidth {
				maxWidth = l
			}
		}
		for _, cmd := range n.Commands {
			if l := len(cmd.Name); l > maxWidth {
				maxWidth = l
			}
		}
		for _, arg := range n.Arguments {
			label := arg.Name
			if strings.TrimSpace(arg.Alternate) != "" {
				label = label + ", " + arg.Alternate
			}
			if l := len(label); l > maxWidth {
				maxWidth = l
			}
		}
	}

	// Add small indent
	maxWidth += 2

	return maxWidth
}

func sanitizeFuncName(s string) string {
	var b bytes.Buffer
	for i, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			if i == 0 && r >= '0' && r <= '9' {
				b.WriteRune('_')
			}
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	res := b.String()
	if res == "" {
		return "_"
	}
	return res
}
